apiVersion: apps/v1
kind: Deployment
metadata:
  name: RVAKSAutodeploy01
  labels:
    app: RVAKSAutodeploy01
  namespace: rvaksworkflow01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RVAKSAutodeploy01
  template:
    metadata:
      labels:
        app: RVAKSAutodeploy01
    spec:
      containers:
        - name: RVAKSAutodeploy01
          image: rvaksregistry01.azurecr.io/rvaksimageworkflow01:latest
          ports:
            - containerPort: 5000