apiVersion: v1
kind: Service
metadata:
  name: RVAKSAutodeploy01
  namespace: rvaksworkflow01
spec:
  type: LoadBalancer
  selector:
    app: RVAKSAutodeploy01
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000